<?php

namespace nazmulpcc\Checkers;

class Verdict
{
    const ACCEPTED              = 'ACCEPTED';
    const WRONG_ANSWER          = 'WRONG_ANSWER';
    const PRESENTATION_ERROR    = 'PRESENTATION_ERROR';
    const RUNTIME_ERROR         = 'RUNTIME_ERROR';
    const MEMORY_LIMIT_EXCEEDED = 'MEMORY_LIMIT_EXCEEDED';
    const TIME_LIMIT_EXCEEDED   = 'TIME_LIMIT_EXCEEDED';
    const INTERNAL_ERROR        = 'INTERNAL_ERROR';
    const RUNTIME_ERROR_SIGFPE  = 'RUNTIME_ERROR_SIGFPE';
    const RUNTIME_ERROR_SIGSEGV = 'RUNTIME_ERROR_SIGSEGV';
    const RUNTIME_ERROR_SIGXFSZ = 'RUNTIME_ERROR_SIGXFSZ';
    const RUNTIME_ERROR_SIGABRT = 'RUNTIME_ERROR_SIGABRT';
}
